// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchmp145GuG7ZwN-fsMdSlWU02hP1ihRA',
    appId: '1:997966389549:web:4c94b1545fd5bc5d9eb3a4',
    messagingSenderId: '997966389549',
    projectId: 'chatapp-c4756',
    authDomain: 'chatapp-c4756.firebaseapp.com',
    storageBucket: 'chatapp-c4756.appspot.com',
    measurementId: 'G-TQPH289R00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGRPZhoGSIzEh5HryaVc78XueYwdPrSg',
    appId: '1:997966389549:android:32c3893bd8f892989eb3a4',
    messagingSenderId: '997966389549',
    projectId: 'chatapp-c4756',
    storageBucket: 'chatapp-c4756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_MeiC-t28GLcHSRAxDZJ7g87E-izOOk',
    appId: '1:997966389549:ios:76bc545bc431d4b99eb3a4',
    messagingSenderId: '997966389549',
    projectId: 'chatapp-c4756',
    storageBucket: 'chatapp-c4756.appspot.com',
    iosClientId: '997966389549-97cresq74l6f8r6osk011tttc7rcti63.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg_MeiC-t28GLcHSRAxDZJ7g87E-izOOk',
    appId: '1:997966389549:ios:76bc545bc431d4b99eb3a4',
    messagingSenderId: '997966389549',
    projectId: 'chatapp-c4756',
    storageBucket: 'chatapp-c4756.appspot.com',
    iosClientId: '997966389549-97cresq74l6f8r6osk011tttc7rcti63.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
